### PR TITLE
Leaderboard

### PR DESCRIPTION
**Pull request by HWaruguru**
Add content to the leaderboard.
Made a draft pull request because I am still working on the leaderboard.
I am still figuring out how to make Vuetify work

Task: [T324935](https://phabricator.wikimedia.org/T324935)

### CODE REVIEW

**Review by nbarnabee — COMMENTED** [review]
Hey, Hannah, just a couple of comments:

If we want to check whether the URL to the user's wikimedia page is working properly we'd need to use actual usernames in the mock data.  Here are some: 

"NicoleLBee"  
"Demo Unicorn"   
"BDavis (WMF)"  
"Sage (Wiki Ed)"    

Those will also be a good test of whether the space replacement is working as expected - and your use of `.split(' ').join('_')` is a much better solution than my regex!

For the :key would it be better to bind it to something like `user.userName`?  There's not actually an id value in the user objects.

**Comment by HWaruguru** [comment]
Hey, Nicole thanks for this I hadn't thought about it in this way. I have tried it with real users and it is working great. Sure let me fix :key.

**Review by nbarnabee — CHANGES_REQUESTED** [review]
Looks great!  I'm so happy about that header ("Toolhunt Leaderboard") section; looking at your work, I finally understand what I was doing wrong when I was working on something similar for the dashboard.

My only thought is that we might want to add an additional attribute to the generated links so that clicking on them won't take the user away from Toolhunt.  `target="_blank"` is the obvious one, but I have literally _just_ discovered that if we use a word _other_ than blank (e.g., `target="_userInfo"`), the browser will open a new tab and then keep using the same tag, which might be preferable.  

For maximum security we could also add `rel="noopener"` to the link as well, though I doubt that wikimedia sites present a risk.

**Comment by nbarnabee** [comment]
Also, right now the toolhub logo is shrinking down ridiculously small on a mobile screen.  I guess we'd either want to set a minimum size or just set it to not display on a small screen.

**Comment by HWaruguru** [comment]
Thank you so much Nicole for the great feedback. I will look and see more about the one with a word other than blank. Also, I think is safer to add the rel="noopener". I will work on the logo I hadn't seen this.

**Comment by HWaruguru** [comment]
Just realized I forgot to edit the logo

**Review by Damilare1 — APPROVED** [review]

**Review by nbarnabee — APPROVED** [review]

**Pull request merged**
