### PR TITLE
Improve UserContributionForm layout

### PR DESCRIPTION
**Pull request by nbarnabee**
This PR addresses [T331274](https://phabricator.wikimedia.org/T331274).

The UserContributionForm was rendering very badly on small screens.  My layout alterations have also changed its appearance on larger screens.  Personally, I like the new look, but could also revert to the older one (input bar and buttons on the same row)

### CODE REVIEW

**Comment by HWaruguru** [comment]
Hi @nbarnabee could you please attach a screenshot of how it appears on your side in a small screen

**Comment by HWaruguru** [comment]
Mine appears to be messed up still

**Comment by nbarnabee** [comment]
Here's what it looks like on my screen, at PC, tablet, and mobile screen widths:
comparison

**Comment by HWaruguru** [comment]
oh wow because in mine it was still messed up

**Comment by HWaruguru** [comment]
Oh sorry I hadn't fetched the changes.. It's working well

**Review by HWaruguru — APPROVED** [review]

**Review by Damilare1 — APPROVED** [review]

**Pull request merged**
